import { DefaultTheme } from 'styled-components';

export const themes: Record<string, DefaultTheme> = {
  light: {
    colors: {
      primaryColor: '#1c1d1f',
      primaryText: '#11052C',
      secondaryColor: '#087ea4',
      secondaryColorText: '#404756',
      secondaryColorTextButton: '#fff',
      buttonPrimaryBg: '#1c1d1f',
      buttonPrimaryColorText: '#fff',
      buttonPrimaryInvertBg: '#fff',
      buttonPrimaryInvertColorText: '#1c1d1f',
      themeText: '#000000',
      white: '#FFFFFF',
      dark: '#282526',
      headerBg: '#1c1d1f',
      headerBoxShadow: 'rgba(100, 100, 111, 0.2) 0px 7px 29px 0px',
      headerBorderColor: 'red',
      progressBarBg: '#f7f9fa',
      progressBarTimerBg: '#d1d7dc',
      progressBarBoxShadow: '0',
      svgIconBg: '#282526',
      svgIconFill: '#FFFFFF',
      radioButtonBorder: '#1c1d1f',
      radioButtonCircleBg: '#eeeeee',
      gray150: '#f7f9fa',
      gray200: '#eeeeee',
      gray300: '#d1d7dc',
      gray450: '#cccccc',
    },
    fonts: {
      anekMalayalam: 'Anek Malayalam',
    }
  },
  dark: {
    colors: {
      primaryColor: '#282526',
      secondaryColor: '#58c4dc',
      secondaryColorText: '#a8a8a8',
      secondaryColorTextButton: '#282526',
      buttonPrimaryBg: '#bdbdbd',
      buttonPrimaryColorText: '#282526',
      buttonPrimaryInvertBg: '#282526',
      buttonPrimaryInvertColorText: '#bdbdbd',
      background: '#282526',
      themeText: '#FFFFFF',
      dark: '#282526',
      headerBg: '#282526',
      headerBoxShadow: 'rgb(32 32 32) 0px 7px 29px 0px',
      headerBorderColor: '#383838',
      progressBarBg: 'transparent',
      progressBarTimerBg: '#313131',
      progressBarBoxShadow: 'rgb(32 32 32) 0px 7px 29px 0px',
      radioButtonBorder: '#383838',
      radioButtonCircleBg: '#403b3b',
      gray450: '#cccccc',
      svgIconBg: '#FFFFFF',
      svgIconFill: '#282526',
    },
    fonts: {
      anekMalayalam: 'Anek Malayalam',
    }
  },
}