import { DefaultTheme } from 'styled-components';

export const themes: Record<string, DefaultTheme> = {
  light: {
    colors: {
      primaryColor: '#1c1d1f',
      primaryText: '#11052C',
      secondaryColor: '#087ea4',
      secondaryColorText: '#404756',
      secondaryColorTextButton: '#fff',
      buttonPrimaryBg: '#1c1d1f',
      buttonPrimaryColorText: '#fff',
      buttonPrimaryInvertBg: '#fff',
      buttonPrimaryInvertColorText: '#1c1d1f',
      themeText: '#000000',
      white: '#FFFFFF',
      dark: '#282526',
      headerBg: '#1c1d1f',
      headerBoxShadow: 'rgba(100, 100, 111, 0.2) 0px 7px 29px 0px',
      headerBorderColor: '#ececed',
      progressBarBg: '#f7f9fa',
      progressBarTimerBg: '#d1d7dc',
      progressBarBoxShadow: '0',
      svgIconBg: '#282526',
      svgIconFill: '#FFFFFF',
      radioButtonBorder: '#1c1d1f',
      radioButtonCircleBg: '#eeeeee',
      gray150: '#f7f9fa',
      gray200: '#eeeeee',
      gray300: '#d1d7dc',
      gray450: '#cccccc',
      result: {
        defaultOptionBg: '#f7f9fa',
        defaultOptionBorder: '#d1d7dc',

        correctOptionBg: '#e3fae4',
        correctOptionText: '#e5ffe6',
        correctOptionBorder: '#4caf50',
        correctBadgeBg: '#4caf50',
        correctBadgeColor: '#e5ffe6',

        incorrectOptionBg: '#ffdcdc',
        incorrectOptionText: '#fff2f2',
        incorrectOptionBorder: 'red',
        incorrectBadgeBg: '#f44336',
        incorrectBadgeText: '#fff2f2',

        correctNotSelectedOptionBg: '#fff9ed',
        correctNotSelectedOptionBorder: 'orange',
        correctNotSelectedOptionText: '#11052C',
        correctNotSelectedBadgeBg: 'orange',
        correctNotSelectedBadgeText: '#fff9ed',
      },
    },
    fonts: {
      anekMalayalam: 'Anek Malayalam',
    }
  },
  dark: {
    colors: {
      primaryColor: '#282526',
      secondaryColor: '#58c4dc',
      secondaryColorText: '#a8a8a8',
      secondaryColorTextButton: '#282526',
      buttonPrimaryBg: '#bdbdbd',
      buttonPrimaryColorText: '#282526',
      buttonPrimaryInvertBg: '#282526',
      buttonPrimaryInvertColorText: '#bdbdbd',
      background: '#282526',
      themeText: '#FFFFFF',
      dark: '#282526',
      headerBg: '#282526',
      headerBoxShadow: 'rgb(32 32 32) 0px 7px 29px 0px',
      headerBorderColor: '#383838',
      progressBarBg: 'transparent',
      progressBarTimerBg: '#313131',
      progressBarBoxShadow: 'rgb(32 32 32) 0px 7px 29px 0px',
      radioButtonBorder: '#383838',
      radioButtonCircleBg: '#403b3b',
      gray450: '#cccccc',
      svgIconBg: '#FFFFFF',
      svgIconFill: '#282526',
      result: {
        defaultOptionBg: '#252122',
        defaultOptionBorder: '#383838',
        correctOptionBg: '#2b6e6233',
        correctOptionBorder: '#455654',
        correctOptionText: '#e5ffe6',
        correctBadgeBg: '#455654',
        correctBadgeColor: '#e5ffe6',

        incorrectOptionBg: '#582521',
        incorrectOptionBorder: '#804c48',
        incorrectOptionText: '#fff2f2',
        incorrectBadgeBg: '#814c49',
        incorrectBadgeText: '#fff2f2',

        correctNotSelectedOptionBg: '#b6570033',
        correctNotSelectedOptionText: '#ffebd8',
        correctNotSelectedOptionBorder: '#765334',
        correctNotSelectedBadgeBg: '#db7d27',
        correctNotSelectedBadgeText: '#fff9ed'
      },
    },
    fonts: {
      anekMalayalam: 'Anek Malayalam',
    }
  },
}